import { Investor } from './types';

// Mock yatırımcı verileri — Supabase'e geçene kadar kullanılacak
export const MOCK_INVESTORS: Investor[] = [
  {
    id: '1',
    name: 'Ali Koç',
    title: 'Kurucu Ortak',
    company: 'Koç Digital Ventures',
    email_verified: true,
    linkedin_url: 'https://linkedin.com/in/alikoc',
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['vc'],
    sectors: ['fintech', 'saas', 'ai'],
    stages: ['seed', 'series_a'],
    min_ticket: 100000,
    max_ticket: 1000000,
    portfolio: ['Getir', 'Trendyol', 'Iyzico'],
    bio: 'Türkiye\'nin önde gelen teknoloji yatırımcılarından. Fintech ve SaaS alanında aktif.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: '2',
    name: 'Elif Yılmaz',
    title: 'Managing Partner',
    company: 'Bosphorus Ventures',
    email_verified: true,
    linkedin_url: 'https://linkedin.com/in/elifyilmaz',
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['vc'],
    sectors: ['ecommerce', 'marketplace', 'logistics'],
    stages: ['pre_seed', 'seed'],
    min_ticket: 50000,
    max_ticket: 500000,
    portfolio: ['HepsiBurada', 'Yemeksepeti'],
    bio: 'E-ticaret ve pazar yeri modellerinde uzman. Erken aşama yatırımcı.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-01-15',
    updated_at: '2024-05-20',
  },
  {
    id: '3',
    name: 'Murat Demir',
    title: 'Angel Investor',
    company: 'Bağımsız',
    email_verified: false,
    location_city: 'Ankara',
    location_country: 'TR',
    investor_type: ['angel'],
    sectors: ['health', 'deeptech'],
    stages: ['pre_seed'],
    min_ticket: 10000,
    max_ticket: 100000,
    portfolio: ['MedTech Ankara'],
    bio: 'Sağlık teknolojilerine odaklanan melek yatırımcı. Ankara ekosisteminde aktif.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-02-01',
    updated_at: '2024-04-15',
  },
  {
    id: '4',
    name: 'Zeynep Aksoy',
    title: 'General Partner',
    company: 'Anatolia Fund',
    email_verified: true,
    linkedin_url: 'https://linkedin.com/in/zeynepaksoy',
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['vc'],
    sectors: ['gaming', 'social', 'ai'],
    stages: ['seed', 'series_a', 'series_b'],
    min_ticket: 200000,
    max_ticket: 2000000,
    portfolio: ['Peak Games', 'Gram Games', 'Dream Games'],
    bio: 'Oyun ve sosyal medya startup\'larına yatırım yapan deneyimli VC.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-01-10',
    updated_at: '2024-06-01',
  },
  {
    id: '5',
    name: 'Can Başaran',
    title: 'CEO',
    company: 'FamilyO Capital',
    email_verified: true,
    location_city: 'İzmir',
    location_country: 'TR',
    investor_type: ['family_office'],
    sectors: ['logistics', 'food', 'ecommerce'],
    stages: ['seed', 'series_a'],
    min_ticket: 500000,
    max_ticket: 5000000,
    portfolio: ['Taze Mutfak', 'JetKurier'],
    bio: 'Ege bölgesinin en büyük aile ofislerinden. Lojistik ve gıda teknolojisine odaklı.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-03-01',
    updated_at: '2024-05-30',
  },
  {
    id: '6',
    name: 'Selin Tunç',
    title: 'Partner',
    company: 'Seed Türkiye',
    email_verified: false,
    linkedin_url: 'https://linkedin.com/in/selintunc',
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['vc'],
    sectors: ['edtech', 'saas'],
    stages: ['pre_seed', 'seed'],
    min_ticket: 25000,
    max_ticket: 250000,
    portfolio: ['Udemy TR', 'KodlaBilim'],
    bio: 'Eğitim teknolojileri ve SaaS alanında aktif. Pre-seed odaklı.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-02-15',
    updated_at: '2024-06-05',
  },
  {
    id: '7',
    name: 'Hakan Öztürk',
    title: 'Founder & Angel',
    company: 'Bağımsız',
    email_verified: true,
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['angel'],
    sectors: ['fintech', 'ai', 'saas'],
    stages: ['pre_seed', 'seed'],
    min_ticket: 15000,
    max_ticket: 150000,
    portfolio: ['PayTR', 'Colendi'],
    bio: 'Eski fintech girişimcisi, şimdi melek yatırımcı. Yapay zeka odaklı fintech\'lere ilgili.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-01-20',
    updated_at: '2024-05-25',
  },
  {
    id: '8',
    name: 'Deniz Kaya',
    title: 'Investment Director',
    company: 'Turkven',
    email_verified: true,
    linkedin_url: 'https://linkedin.com/in/denizkaya',
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['pe'],
    sectors: ['ecommerce', 'food', 'health'],
    stages: ['series_a', 'series_b'],
    min_ticket: 1000000,
    max_ticket: 10000000,
    portfolio: ['Domino\'s TR', 'Sağlıkçım'],
    bio: 'Büyüme aşaması odaklı özel sermaye yatırımcısı. E-ticaret ve sağlık sektöründe deneyimli.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-03-10',
    updated_at: '2024-06-01',
  },
  {
    id: '9',
    name: 'Ayşe Çelik',
    title: 'Melek Yatırımcı',
    company: 'Galata Business Angels',
    email_verified: true,
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['angel'],
    sectors: ['social', 'edtech', 'marketplace'],
    stages: ['pre_seed'],
    min_ticket: 5000,
    max_ticket: 50000,
    portfolio: ['SocialBuzz', 'EğitimX'],
    bio: 'Kadın girişimcilere odaklanan melek yatırımcı. Sosyal etki projeleri öncelikli.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-04-01',
    updated_at: '2024-06-10',
  },
  {
    id: '10',
    name: 'Burak Şahin',
    title: 'VP Investments',
    company: 'İstanbul Venture Partners',
    email_verified: true,
    linkedin_url: 'https://linkedin.com/in/buraksahin',
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['vc'],
    sectors: ['ai', 'deeptech', 'saas'],
    stages: ['seed', 'series_a'],
    min_ticket: 250000,
    max_ticket: 3000000,
    portfolio: ['AIStartup', 'DeepSense', 'CloudTR'],
    bio: 'Yapay zeka ve derin teknoloji alanlarında uzman. Teknik due diligence konusunda güçlü.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-02-20',
    updated_at: '2024-06-08',
  },
  {
    id: '11',
    name: 'Fatma Güneş',
    title: 'Kurucu',
    company: 'AngelEffect',
    email_verified: true,
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['angel'],
    sectors: ['health', 'food', 'social'],
    stages: ['pre_seed', 'seed'],
    min_ticket: 10000,
    max_ticket: 75000,
    portfolio: ['FreshFarm', 'HealthApp'],
    bio: 'Kadın girişimciler için melek yatırım ağı kurucusu. Sürdürülebilirlik odaklı.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-05-01',
    updated_at: '2024-06-12',
  },
  {
    id: '12',
    name: 'Emre Yıldız',
    title: 'Managing Director',
    company: 'Endeavor Catalyst TR',
    email_verified: true,
    linkedin_url: 'https://linkedin.com/in/emreyildiz',
    location_city: 'İstanbul',
    location_country: 'TR',
    investor_type: ['vc'],
    sectors: ['fintech', 'marketplace', 'logistics'],
    stages: ['series_a', 'series_b'],
    min_ticket: 500000,
    max_ticket: 5000000,
    portfolio: ['Insider', 'Modanisa', 'BiTaksi'],
    bio: 'Büyüme aşaması VC. Türkiye\'nin en hızlı büyüyen şirketlerine yatırım yapıyor.',
    locale: 'tr',
    is_active: true,
    created_at: '2024-01-05',
    updated_at: '2024-06-15',
  },
];
